Properly handle casts
revng/revng-qa pull request #25
Opened 2024-04-30 09:23 UTC by dwarfyresearch

- Add test for C casts

2024-05-13 15:44 UTC, aleclearmind requested changes

2024-05-13 15:44 UTC, aleclearmind commented on share/revng/test/tests/analysis/Decompilation/x86-64/reduce-c-casts.c
> +// Copyright (c) rev.ng Labs Srl. See LICENSE.md for details.
Outdated

2024-05-13 15:44 UTC, aleclearmind commented on share/revng/test/tests/analysis/Decompilation/x86-64/reduce-c-casts.c
> +__attribute__((weak)) unsigned return_value() {
`#define WEAK __attribute__((weak))`

2024-05-16 21:41 UTC, pfez commented
Merged in d790789c25169a9a57e669a9e569760cb57120bd

Thanks.

2024-05-16 21:41 UTC, closed without merging